catalog: shm
schema: pid
preprocess:
  raw_path: ./assets/shell_facility_drawings.pdf
  processed_path: ./processed_pdfs/
  dpi: 200
  tile_width_px: 4096
  tile_height_px: 2048
  overlap_px: 512
parse:
  output_path: ./parsed_pdfs/
  example_path: ./examples/
  fm_endpoint: databricks-claude-sonnet-4
  temperature: 0.1
  top_p: 0.1
  max_retries: 3
  retry_delay_s: 1
  num_few_shot_examples: 2
  metadata_prompt: |
    You are an expert in parsing process and instrumentation diagrams and engineering drawings. You will be given a full drawing and a zoomed in excerpt of the title block and your task is to extract metadata including:

    - drawing name
    - title
    - revision
    - date (YYYYMMDD)
    - locations
    - organization
    - legacy numbers
    - moc numbers
    - whether there is an engineering stamp (has_stamp)

    Guidelines:
    - Do not extract tags or equipment numbers and focus solely on the metadata in the title block. 
    - Only return information from the drawing and do not try to interpet or invent a response.
    - The revision is usually in the lower right corner besdie the drawing name
    - The data is often accompanies by "ISSUED FOR ..."
    - Legacy numbers are drawings numbers that differ from the main drawing name in the title block
    - MOC (management of change) numbers are often in the comments or diagram area

    IMPORTANT: Respond with valid JSON only. Do not wrap in markdown code blocks or add any explanatory text. Start directly with { and end with }.
  metadata_example: |
    {
      drawing_name: MRP-250-PID-PR-001103
      title: AREA 250 - FROTH TREATMENT 2ND STAGE SETTLER TRAIN 1 PIPING AND INSTRUMENTATION DIAGRAM
      revision: 3g
      date: 20250811
      locations: [ALB-MRP-250]
      organization: CNRL
      legacy_number: []
      moc_numbers: [22193534]
      has_stamp: True
    }
  tag_prompt: |
    You are an expert in parsing process and instrumentation diagrams and engineering drawings. You will be given a tile of drawing and your task is to extract the equipment tags, line numbers, incoming and outgoing stream, management of change (MOC) numbers, and any free text comments outside of these items. 

    Guidelines:
    - MOC (management of change) numbers are often in the comments or diagram area
    - Incoming streams are denoted by a block arrow with text pointing inside the tile. 
    - Outgoing streams are denoted by a block arrow with text pointing outside the tile.
    - Only extract the number from the streams (e.g. 241.005)
    - Line numbers are often directly below a line and usually have a size (e.g. 4\")
    - Equipment numbers are often on multiple lines within a shape (square, circle, diamond) with some letter designation (PT-250)
    - Only extract equipment numbers that have a number (e.g. not PP)

    IMPORTANT: Respond with valid JSON only. Do not wrap in markdown code blocks or add any explanatory text. Start directly with { and end with }.
  tag_example: |
    {
      equipment_tags: [250-LT-1610, 250-MV-1630, 250-OW-6\\"-A4A-1202, 250-PU-105B],
      line_tags: [14\"-SU-241001-SEG],
      incoming_streams: [240.003]
      outgoing_streams: [241.005, 241.006],
      moc_numbers: [102393],
      comments: [
        FEED/STEAM PREHEATER SPRAY ATTEMPERATOR,
        DESIGN TEMP: 150C, DESIHN PRESS 7350 kPa
      ],
    }
